### ISSUE TITLE
Hi,Could you tell me how to combine multiple videos?

### ISSUE THREAD

**Issue by gitshaozhong** [SuTanTank/VideoStitchingViaShakinessRemoving#1]
For example,I want to combine more than three videos, can I combine two videos firstly,and then combine the others?

**Comment by SuTanTank** [comment]
I didn't design a multi video stitching framework. But in practice, you can stitching two videos together first, then stitch another one, which is how I did when making the demo videos, which include stitching results from more than 2 input videos.

**Comment by gitshaozhong** [comment]
Thanks very much for your answer.
