### ISSUE TITLE
图像拼接不上

### ISSUE THREAD

**Issue by EuterpeK** [SuTanTank/VideoStitchingViaShakinessRemoving#5]
我用两个不同的设备拍了两个独立抖动的视频，用该代码运行后，图像共同区域无法对齐并且运行出来的图像扭曲比较严重，请问为什么会出现这样的情况？是因为设备不同以及拍摄的时候两台设备距离比较远（两三米）造成两段视频视差比较大吗？我读了一下论文，似乎视差大不会有很大的问题，所以想请您分析一下原因。

**Comment by SuTanTank** [comment]
可以把视频缩短一点，然后看看每个部分运行的正不正常。可以的话，发到这里也行

**Comment by EuterpeK** [comment]
- [ ] [`[](url)`]([url](url))

**Comment by EuterpeK** [comment]
您好，感谢您上次的解答，增大padding后确实就正确了。
我按您写的README.txt操作之后得到的D1.jpg好像是只找到了右边的一条缝，剩下的D2.jpg, D3jpg，D4.jpg等等都只剩左半部分或者右半边部分图片，请问这是怎么回事？
我想给您发邮件让您看看我的部分运行结果，但是发了好几次都被您的邮件服务商判定为垃圾邮件，所以只能给您留言。

**Comment by SuTanTank** [comment]
应该是GraphCut这部分有问题，我尝试debug了一下，但现在看当时的代码，觉得写的很烂，所以懒得去改了。文章里面思路是清楚的，那些结果也是用这一部分代码（至少是graphcut的那一部分）跑出来的。你也可以尝试去自己实现这一部分，毕竟这部分不算是文章的主要贡献。

**Comment by EuterpeK** [comment]
好的，谢谢您。我运行出来的结果只能识别出左边或者右边的接缝。我想问一下  Graphcut一次只能识别一个接缝吗？如果我想两条都识别并融合，应该怎么操作？

**Comment by SuTanTank** [comment]
只有一条缝，穿过重合区域。大致思路可以看这个 https://zhuanlan.zhihu.com/p/150732781

**Comment by EuterpeK** [comment]
> 只有一条缝，穿过重合区域。 浅浅可以看这个[https://zhulan.zhihu.com/p/15732781](https://zhuanlan.zhihu.com/p/150732781)

非常感谢您一直以来的耐心解答！！！对我很有帮助。

**Comment by xux0u** [comment]
> 您好，感谢您上次的解答，增大padding后确实就正确了。 我按您写的README.txt操作之后得到的D1.jpg好像是只找到了右边的一条缝，剩下的D2.jpg, D3jpg，D4.jpg等等都只剩左半部分或者右半边部分图片，请问这是怎么回事？ 我想给您发邮件让您看看我的部分运行结果，但是发了好几次都被您的邮件服务商判定为垃圾邮件，所以只能给您留言。

请问您padding设置的多少？

**Comment by EricYHan** [comment]
> > 只有一条缝，穿过重合区域。 浅浅可以看这个[https://zhulan.zhihu.com/p/15732781](https://zhuanlan.zhihu.com/p/150732781)
> 
> 非常感谢您一直以来的耐心解答！！！对我很有帮助。

请问您解决了拼缝的问题吗？非常感谢

**Comment by Sakura1609** [comment]
> > > 只有一条缝，穿过重合区域。 浅浅可以看这个[https://zhulan.zhihu.com/p/15732781](https://zhuanlan.zhihu.com/p/150732781)
> > 
> > 
> > 非常感谢您一直以来的耐心解答！！！对我很有帮助。
> 
> 请问您解决了拼缝的问题吗？非常感谢

应该是FillHole有问题，得到的Mask不太对，修改一下FillHole的逻辑最后生成了还算可以的图像
